df.at[0,'Octant ID'] = 'Overall Count'
#  df.at[0,'1'] = list(df['Octant']).count(1)
#  df.at[0,'-1'] = list(df['Octant']).count(-1)
#  df.at[0,'2'] = list(df['Octant']).count(2)
#  df.at[0,'-2'] = list(df['Octant']).count(-2)
#  df.at[0,'3'] = list(df['Octant']).count(3)
#  df.at[0,'-3'] = list(df['Octant']).count(-3)
#  df.at[0,'4'] = list(df['Octant']).count(4)
#  df.at[0,'-4'] = list(df['Octant']).count(-4)